### PR TITLE
Tidy up sum file

### PR DESCRIPTION
**Pull request by hugares**

### CODE REVIEW

**Comment by eyalbe4** [comment]
@hugares,
What is the purpose of this change.
Looks like *gofrog* is duplicated in the sum file now.
```
github.com/jfrog/gofrog v1.0.4 h1:jtMkCBEsGOC/URxeHXGLZNFjOAMfvDn0UhN+0uXo1GA=
github.com/jfrog/gofrog v1.0.4/go.mod h1:4Caxvc8B2K1A798G1Ne+SsUICRPPre4GpgcFqj+EXJ8=
github.com/jfrog/gofrog v1.0.5 h1:pEJmKZ9XgvQH2a8WCqAEeUDSXBCKBMN90QzOiOhBTIs=
github.com/jfrog/gofrog v1.0.5/go.mod h1:4Caxvc8B2K1A798G1Ne+SsUICRPPre4GpgcFqj+EXJ8=
```

**Comment by hugares** [comment]
The purpose on this change is to start with a clean base line before I do my other PR. This change was done by running `go mod tidy`. The duplicated entry is because 2 different version of gofrog as used

**Comment by eyalbe4** [comment]
I see @hugares. Thanks. 
I suggest we align all packages to use v1.0.5 of gofrog.
We'll merge your PRs as needed.

**Comment by hugares** [comment]
Here is the PR to update gofrog version used by jfrog-client-go: https://github.com/jfrog/jfrog-client-go/pull/88

Once that PR is merged and a new version of jfrog-client-go is released, I will update this project

**Comment by hugares** [comment]
superseded by https://github.com/jfrog/gocmd/pull/21

**Pull request closed without merging**
